# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "192.168.178.57"
    - "127.0.0.1"
    - "172.26.0.0/24"
    - "10.42.0.0/24"

homeassistant:
  customize: !include customize.yaml
  external_url: !secret http.external_url

lovelace:
  mode: yaml
  resources: !include lovelace-resources.yaml

logger:
  default: info

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
input_boolean: !include_dir_merge_named input_boolean/
binary_sensor: !include_dir_merge_list binary_sensor/


vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum.token
    token: !secret vacuum.token


telegram_bot:
  - platform: polling
    api_key: !secret telegram.api_key
    allowed_chat_ids:
      - !secret telegram.carsten.id
      - !secret telegram.daniela.id

notify:
  - name: carsten
    platform: telegram
    chat_id: !secret telegram.carsten.id
  - name: daniela
    platform: telegram
    chat_id: !secret telegram.daniela.id

device_tracker:
  - platform: fritz
    host: !secret fritz.ip
    password: !secret fritz.pw
    new_device_defaults:
      track_new_devices: false
    consider_home: 60
    interval_seconds: 25
  - platform: tado
    username: !secret tado.user
    password: !secret tado.pw
    home_id: 476475

# Text to speech
tts:
  - platform: google_translate

# switch:
#   - platform: rest
#     name: TV
#     resource: http://cec-control:5000/device/0/power
#     body_on: '{"state":"on"}'
#     body_off: '{"state":"off"}'
#     is_on_template: '{{ value_json.state == "starting" or value_json.state == "on" }}'
